### ISSUE TITLE
關於標點位置的問題

### ISSUE THREAD

**Issue by larachung** [lxgw/LxgwZhiSong#1]
尊敬的開發者，

首先對您在霞鶩緻宋等項目上的辛勤工作表示衷心的感謝。我注意到當前版本中，橫書標點的位置並非居中，而縱書標點則是居中的（見下圖）。這兩種設計在不同的排版傳統中有着各自的排版適用性和美學考量。

<img width="165" alt="image" src="https://github.com/lxgw/LxgwZhiSong/assets/103840434/7c048a0e-c147-4f54-a9d7-d35ac26ffb1f"> <img width="121" alt="image" src="https://github.com/lxgw/LxgwZhiSong/assets/103840434/776ddb41-b3c0-41e2-9e40-0fbbd46c4e49">

在現行的繁體中文排版習慣裏標點多為居中，但標點的居中並非絕對，而是源於鉛字時代部分印刷廠為了能在縱橫排版時使用同一套標點活字的一種實用性調整。因此，縱書標點居中可能不適合部分追求傳統排版效果的用戶，而橫書標點不居中則又不適合追求現行繁體中文習慣的用戶，结果可能會「兩頭不討好」。

所以我想詢問一下，是否有計劃推出兩個不同版本的字體，一個保留原版 IPAex 明朝標點位置，另一個則將縱橫版本標點全部修改為居中，以迎合更廣泛的用戶習慣？

此外，還有一個關於冒號「：」在非全置中標點中的縱書轉向問題。和一律不轉的分號「；」不同，冒號在緃書時是否轉向並無定論。不同的字體項目可能會採取不同的處理方式。例如，思源宋體日文版和 IPAex 明朝就展示了兩種不同的風格（見下圖）。請問是否考慮通過 ss01 變體或再推出第三個單獨版本來滿足不同用戶的需求？
<img width="25" alt="image" src="https://github.com/lxgw/LxgwZhiSong/assets/103840434/dfdd899c-8be6-45be-97e3-b5518ceac1ed"> <img width="19" alt="image" src="https://github.com/lxgw/LxgwZhiSong/assets/103840434/acafd84a-d4b3-43e1-9f69-4407e5471b9d">

[霞鶩傳承晰黑](https://github.com/lxgw/LxgwZhiSong)的情況相同。

再次感謝您對字體設計的貢獻，期待您的回覆。

**Comment by lxgw** [comment]
後續可能會考慮統一爲置中標點，與「霞鶩文楷 TC」一致。

同時維護兩個版本的字體文件會增加工作量，因此只能選擇其中一個。
