### ISSUE TITLE
是否有計劃添加 Kerning 信息

### ISSUE THREAD

**Issue by larachung** [lxgw/LxgwZhiSong#3]
<img width="524" alt="image" src="https://github.com/user-attachments/assets/d8c4a001-adee-4f0b-999f-54bcab2b0dd7">

請問是否有計劃為圖中等較明顯的 pairs 添加 kerning 信息。在考慮中西文共用碼位、減少嵌入字體數量、保持風格統一等情況下並不方便為英數部分單獨指定字體，此時缺少 kerning 還是很「搶眼」的。雖然像思源字體一樣添加十分完善的 kerning 信息是一個困難的大工程，但僅對如 VA 等較明顯的少數 pairs 做處理或許可以在投入較小的情況下獲得較高的收益。

**Comment by lxgw** [comment]
原始字体 IPAexMincho 不包含 Kerning，本字体也不包含。
