### ISSUE TITLE
間隔號的位置與寬度

### ISSUE THREAD

**Issue by larachung** [lxgw/LxgwZhiSong#4]
<img width="418" alt="image" src="https://github.com/user-attachments/assets/3ca84265-33ff-41f2-bbc4-f9fe499beef7" />
<img width="82" alt="image" src="https://github.com/user-attachments/assets/6e7563c5-973a-4f89-b3a3-e0ea2251f87e" />

以上是常被用做中文間隔號的三個字符——·`U+00B7 MIDDLE DOT`、・`U+30FB KATAKANA MIDDLE DOT`、．`U+FF0E FULLWIDTH FULL STOP`，後兩者正常，前者即使按照[中國國標](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)5.1.7 中推荐的半字寬也太窄了，且垂直方向不居中，竪排時尤為明顯。建議調整為半字寬且垂直居中。晰黑同樣存在此情況。

**Comment by lxgw** [comment]
這個問題，個人目前暫時保留原始設計。
